package:
  name: conda-which
  version: 0.2.1

source:
  url: https://github.com/kelvinou01/{{ name }}/archive/refs/tags/{{ version }}.tar.gz

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python
    - conda
    - termcolor

  test:
    - pytest

about:
  home: https://github.com/kelvinou01/conda-which
  license: MIT
  license_file: LICENSE
  summary: Which package does this file belong to?

extra:
  recipe-maintainers:
    - kelvinou01
