package:
  name: conda-which
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.8

  run:
    - python >=3.8
    - conda
    - termcolor

about:
  home: https://github.com/kelvinou01/conda-which
  license: BSD-3-Clause
  summary: Which package does this file belong to?
