[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "conda-which"
version = "0.1.0"
description = "What package does this file belong to?"
requires-python = ">=3.8"
dependencies = ["conda", "termcolor"]

[project.entry-points.conda]
conda-example-plugin = "conda_which"

[tool.setuptools]
py-modules = ["conda_which"]
