name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.8'

    - name: Create and activate conda environment
      run: |
        conda create --name test-env python=3.8 -y
        conda activate test-env
        echo "conda activate test-env" >> $GITHUB_ENV  # Export env activation

    - name: Install dependencies
      run: pip install -e .

    - name: Run tests
      run: pytest test.py -vv
